language: node_js

node_js:
  - "10"

preinstall: npm config set package-lock false

script:
  - npm run test
  - npm run stylelint
  - npm run eslint

notifications:
  email: false

before_deploy: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build
  on:
    branch: master
